use_frameworks!

platform :ios, '8.0'

target 'GDCpuModule_Example' do
  pod 'GDCpuModule', :path => '../'
  target 'GDCpuModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
